### ISSUE TITLE
Lab 12 has Lab 8 content

### ISSUE THREAD

**Issue by hguerrero** [RedHat-Middleware-Workshops/bpmsuite-6-workshop#1]
Document labeled Lab 12 has Lab 8 content instead on how to deploy on kie-server

**Comment by DuncanDoyle** [comment]
Thanks for reporting @hguerrero, there was another lab12 (the correct one) already available. This one seemed like a draft lab that accidentally made it into the repo. Fixed with this commit: https://github.com/RedHat-Middleware-Workshops/bpmsuite-6-workshop/commit/350ddd46ceb3958f7aa2f7e23fa61f76d7e1026e
